// Dungeon Mode's built-in floor settings, from dungeon.json (the same
// format the config editor's Dungeon Floors page takes; see
// src/game/dungeonConfigFile.ts). A mistake in the file throws on load
// naming the field at fault, which fails src/data/dungeon.test.ts.

import { parseDungeonSettings } from '../game/dungeonConfigFile.ts';
import type { DungeonConfig, DungeonSettings } from '../game/dungeonConfigs.ts';
import dungeonText from './dungeon.json?raw';

// The file as written, which the config editor offers as a download.
export const DUNGEON_TEXT: string = dungeonText;

// Every floor is test-generated by dungeon.test.ts instead of on each load.
export const DUNGEON_SETTINGS: DungeonSettings = parseDungeonSettings(DUNGEON_TEXT, { checkMaps: false });

export const DUNGEON_CONFIGS: readonly DungeonConfig[] = DUNGEON_SETTINGS.floors;
