// Warband Mode's built-in regions, from regions.json (the same format
// the config editor's Regions page takes; see
// src/game/warband/regionsFile.ts). A mistake in the file throws on load
// naming the field at fault, which fails src/data/regions.test.ts.

import { parseRegionSettings } from '../game/warband/regionsFile.ts';
import type { RegionConfig, RegionSettings } from '../game/warband/regions.ts';
import regionsText from './regions.json?raw';

// The file as written, which the config editor offers as a download.
export const REGIONS_TEXT: string = regionsText;

// Every region is test-generated by regions.test.ts instead of on each load.
export const REGION_SETTINGS: RegionSettings = parseRegionSettings(REGIONS_TEXT, { checkMaps: false });

export const REGION_CONFIGS: readonly RegionConfig[] = REGION_SETTINGS.regions;
